# .github/workflows/copy-file-to-other-repo.yml
name: Copy File to Another Repo

on: 
  push:
    branches: 
      - master

  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shivani repo
        uses: actions/checkout@v4

      - name: Checkout sample repo
        uses: actions/checkout@v4
        with:
          repository: shivanihamilpur/sample
          path: sample

      - name: Copy file to sample repo
        run: |
          cp shivani/gitfile.txt ./sample/

      - name: Commit and push changes
        run: |
          cd sample-repo
          git config user.name "shivanihamilpur"
          git config user.email "shivanihamilpur@gmail.com"
          git add -A .
          git commit -m "Copy file from shivani repo"
          git push
