name: Copy updated OpenAPI file

# only run this workflow when the
on: 
  push:
    branches: 
      - master

jobs:
  copy_openapi_file_to_notehub_js: 
    runs-on: ubuntu-latest
    steps:
    # check out shivani project
    - name: Check out Notehub project
      uses: actions/checkout@v3
    # check out sample project     - name: Check out Notehub JS project
    - name: Check out Notehub JS project
      uses: actions/checkout@v3
      with:
        repository: shivanihamilpur/sample
        path: ./sample
    # make a copy the of the file from Shivani repo
    - name: Copy file
      run: bash ./.github/scripts/copy-file.sh
      env:
        DESTINATION_PATH: ./sample/
    # make a branch in notehub-js repo and push the copy of the openapi file there
    - name: Push to notehub-js repo
      run: bash ./.github/scripts/push-file.sh
      env:
        BRANCH: feat/copying-file-from-shivani
