# .github/workflows/copy-file-to-other-repo.yml
name: Copy File to Another Repo

on: 
  push:
    branches: 
      - master
      
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shivani repo
        uses: actions/checkout@v4

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          repository: shivanihamilpur/test
          path: test

      - name: Copy file to test repo
        run: |
          cp shivani/gitfile.txt ./test/

      - name: Commit and push changes
        run: |
          cd test-repo
          git config user.name "shivanihamilpur"
          git config user.email "shivanihamilpur@gmail.com"
          git add -A .
          git commit -m "Copy file from shivani repo"
          git push
